<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Category extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        check_is_login();
        $this->load->model('Category_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'category/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'category/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'category/index.html';
            $config['first_url'] = base_url() . 'category/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Category_model->total_rows($q);
        $category = $this->Category_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'category_data' => $category,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'main_title' => 'Kategori',
            'sub_title' => 'Data Kategori',
            'codejs' => 'category/codejs',
            'content' => 'category/category_list',
        );
        $this->load->view('template', $data);
    }

    public function quickAddCategory()
    {
        $data = array(
            'name' => $this->input->post('name',TRUE),
            'description' => $this->input->post('deskripsi',TRUE),
        );

        $this->db->insert('category',$data);

        $id = $this->db->insert_id();

        $data = $this->Category_model->get_by_id($id);

        $result = array(
            'id' => $data->id,
            'name' => $data->name
        );

        echo json_encode($result);
    }
    
    public function create_action() 
    {

        $data = array(
		'name' => $this->input->post('name',TRUE),
		'description' => $this->input->post('deskripsi',TRUE),
	    );

        $this->Category_model->insert($data);
        $this->session->set_flashdata('type', 'success');
        $this->session->set_flashdata('message', 'Data berhasil ditambah');
        redirect(site_url('category'));
        
    }
    
    public function update($id) 
    {
        $row = $this->Category_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('category/update_action'),
		'id' => set_value('id', $row->id),
		'name' => set_value('name', $row->name),
	    );
            $this->load->view('category/category_form', $data);
        } else {
            $this->session->set_flashdata('type', 'failed');
            $this->session->set_flashdata('message', 'Data tidak ditemukan');
            redirect(site_url('category'));
        }
    }
    
    public function update_action() 
    {

        $id = $this->input->post('idkategori',TRUE);
        $data = array(
		    'name' => $this->input->post('name',TRUE),
		    'description' => $this->input->post('deskripsi',TRUE),
	    );

        $this->Category_model->update($id, $data);
        $this->session->set_flashdata('type', 'success');
        $this->session->set_flashdata('message', 'Data berhasil diubah');
        redirect(site_url('category'));
    }
    
    public function delete($id) 
    {
        $row = $this->Category_model->get_by_id($id);

        if ($row) {
            $this->Category_model->delete($id);

            $this->session->set_flashdata('type', 'success');
            $this->session->set_flashdata('message', 'Data berhasil dihapus');
            redirect(site_url('category'));
        } else {
            $this->session->set_flashdata('message', 'Data tidak ditemukan');
            $this->session->set_flashdata('type', 'failed');
            redirect(site_url('category'));
        }
    }

}

/* End of file Category.php */
/* Location: ./application/controllers/Category.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-18 06:24:35 */
/* http://harviacode.com */