<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Unit extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        check_is_login();
        $this->load->model('Unit_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'unit/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'unit/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'unit/index.html';
            $config['first_url'] = base_url() . 'unit/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Unit_model->total_rows($q);
        $unit = $this->Unit_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'unit_data' => $unit,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'main_title' => 'Unit',
            'sub_title' => 'Unit list',
            'codejs' => 'unit/codejs',
            'content' => 'unit/unit_list',
        );
        $this->load->view('template', $data);
    }
    
    public function create_action() 
    {
        $data = array(
            'kode_unit' => $this->input->post('kode_unit',TRUE),
            'name' => $this->input->post('name',TRUE),
	    );

            $this->Unit_model->insert($data);
            $this->session->set_flashdata('type', 'success');
            $this->session->set_flashdata('message', 'Data berhasil ditambah');
            redirect(site_url('unit'));
    }
        
    public function update_action() 
    {
        $id = $this->input->post('idunit');
        $data = array(
		'kode_unit' => $this->input->post('kode_unit',TRUE),
		'name' => $this->input->post('name',TRUE),
	    );

        $this->Unit_model->update($id, $data);
        $this->session->set_flashdata('message', 'Data berhasil diubah');
        $this->session->set_flashdata('type', 'success');
        redirect(site_url('unit'));
    }
    
    public function delete($id) 
    {
        $row = $this->Unit_model->get_by_id($id);

        if ($row) {
            $this->Unit_model->delete($id);
            $this->session->set_flashdata('message', 'Data berhasil dihapus');
            $this->session->set_flashdata('type', 'success');
            redirect(site_url('unit'));
        } else {
            $this->session->set_flashdata('message', 'Data tidak ditemukan');
            $this->session->set_flashdata('type', 'failed');
            redirect(site_url('unit'));
        }
    }

    public function _rules() 
    {
        $this->form_validation->set_rules('kode_unit', 'kode unit', 'trim|required');
        $this->form_validation->set_rules('name', 'name', 'trim|required');
        $this->form_validation->set_rules('created', 'created', 'trim|required');
        $this->form_validation->set_rules('updated', 'updated', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Unit.php */
/* Location: ./application/controllers/Unit.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-27 18:14:39 */
/* http://harviacode.com */