<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Customer_model extends CI_Model
{

    public $table = 'customer';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        if(getuser()->level=="admin"){
            $this->datatables->select('id,customer.id_customer,name_customer,IF(gender="l","Laki-laki","Perempuan") as gender,address,phone,ifnull(sum(total_sales),0) as total,create_at,update_at');
            $this->datatables->from('customer');
            //add this line for join
            $this->datatables->join('sales', 'sales.id_customer = customer.id_customer','left');
            $this->datatables->where('id != ',1);
            $this->datatables->group_by('customer.id_customer');
            $this->datatables->add_column('action', '
                                    <button class="btn btn-xs bg-teal btn-ubah-customer" type="button" data-id="$1" data-id_customer="$2" data-name="$3" data-gender="$4" data-address="$5" data-phone="$6"><i class="fa fa-edit"></i> Ubah</button>'.' '.
                                    anchor(site_url('customer/delete/$1'),'<i class="fa fa-trash"></i> Hapus','class="btn btn-xs btn-danger" onclick="javasciprt: return confirm(\'Apa anda yakin ?\')
                                "'), 'id,id_customer,name_customer,gender,address,phone');
            return $this->datatables->generate();
        }else{
            $this->datatables->select('id,customer.id_customer,name_customer,IF(gender="l","Laki-laki","Perempuan") as gender,address,phone,ifnull(sum(total_sales),0) as total,create_at,update_at');
            $this->datatables->from('customer');
            //add this line for join
            $this->datatables->join('sales', 'sales.id_customer = customer.id_customer','left');
            $this->datatables->where('id != ',1);
            $this->datatables->group_by('customer.id_customer');
            $this->datatables->add_column('action', '-', '');
            return $this->datatables->generate();
        }
    }

    // get all
    function get_all()
    {
        $this->db->where('id !=', 1);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_customer', $q);
	$this->db->or_like('name_customer', $q);
	$this->db->or_like('gender', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_customer', $q);
	$this->db->or_like('name_customer', $q);
	$this->db->or_like('gender', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Customer_model.php */
/* Location: ./application/models/Customer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-11 09:38:25 */
/* http://harviacode.com */